---
    name: Publish Stable Image
    
    on:
      schedule:
        - cron: '0 2 * * 0'
      push:
        paths:
          - 'Dockerfile'
        branches:
          - main
      workflow_dispatch:
    
    jobs:
      release-stable:
        name: build and push stable image
        runs-on: ubuntu-latest
    
        steps:
    
          - uses: actions/checkout@v4
  
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3        
    
          - name: Login to Github Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Generate Docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ghcr.io/${{ github.repository }}
  
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              file: Dockerfile
              cache-from: type=gha
              cache-to: type=gha
              pull: true
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              platforms: linux/amd64,linux/arm64