---
    name: Publish Stable Image
    
    on:
      schedule:
        - cron: '0 2 * * 0'
      push:
        paths:
          - 'Containerfile'
        branches:
          - latest
      workflow_dispatch:
    
    jobs:
      release-stable:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
  
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Generate metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ghcr.io/${{ github.repository }}
              labels: |
                org.opencontainers.image.title=stable
                org.opencontainers.image.vendor=saturn-core
                org.opencontainers.image.description=Base image for Saturn using ubuntu's rolling release
                org.opencontainers.image.authors=saturn-core
                org.opencontainers.image.license=GPL-3.0+

          - name: Buildah Build
            id: build-image
            uses: redhat-actions/buildah-build@v2
            with:
              containerfiles: |
                ./Containerfile
              oci: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              platforms: linux/amd64,linux/arm64

          - name: Push to Github Registry
            id: push-image
            uses: redhat-actions/push-to-registry@v2
            with:
              image: ${{ steps.build-image.outputs.image }}
              tags: ${{ steps.build-image.outputs.tags }}
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
